global:
    scrape_interval: 15s
    scrape_timeout: 10s

scrape_configs:
    - job_name: 'Ping'
      metrics_path: /probe
      params:
        module: [ping_mod]
      static_configs:
        - targets:
          - google.com
          - amazon.com
          - telekom.de
          - opendns.com
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: blackbox-exporter:9115
